flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.1
- clock-0.7.2
- mtl-2.2.1
- optparse-applicative-0.13.0.0
- parsec-3.1.11
- regex-base-0.93.2
- regex-tdfa-1.2.2
- stm-2.4.4.1
- tagged-0.8.5
- tasty-0.11.1
- tasty-hunit-0.9.2
- text-1.2.2.1
- transformers-compat-0.5.1.4
- unbounded-delays-0.1.0.9
resolver: ghc-8.0.2
