flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:

# Pidgin dependencies
- llvm-hs-4.2.0
- llvm-hs-pure-4.1.0.0
- monad-st-0.2.4.1
- mtl-2.2.1

- attoparsec-0.13.2.0
- exceptions-0.8.3
- scientific-0.3.5.1
- stm-2.4.4.1
- text-1.2.2.2
- transformers-compat-0.5.1.4
- utf8-string-1.0.1.1
- hashable-1.2.6.1
- integer-logarithms-1.0.2
- primitive-0.6.2.0

# Test dependencies
- tasty-0.11.2.3
- tasty-hunit-0.9.2

- ansi-terminal-0.6.3.1
- async-2.1.1.1
- clock-0.7.2
- optparse-applicative-0.14.0.0
- regex-tdfa-1.2.2
- tagged-0.8.5
- unbounded-delays-0.1.1.0
- ansi-wl-pprint-0.6.8.1
- parsec-3.1.11
- regex-base-0.93.2

resolver: ghc-8.2.1

